/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running project. It is checked in here
// so TypeScript has the expected references before the first local install.
